### ISSUE TITLE
Method Signature Mismatch for reconciler

### ISSUE THREAD

**Issue by nitishfy** [akuity/kargo#3549]
Look at the following pieces of code:

- https://github.com/akuity/kargo/blob/main/internal/controller/stages/regular_stages.go#L171
- https://github.com/akuity/kargo/blob/main/internal/controller/warehouses/warehouses.go#L96

It appears that `GenerationChangedPredicate` defines the Update method with a parameter named e, whereas `TypedPredicate[object]` expects an unnamed parameter. This results in an incompatibility when used in a generic context. This is the error typically received:

```
Cannot use 'predicate.GenerationChangedPredicate{}' (type predicate.GenerationChangedPredicate) as the type TypedPredicate[object] 
Type does not implement 'TypedPredicate[object]' need the method: Update(event.TypedUpdateEvent[object]) bool 
have the method: Update(e event.TypedUpdateEvent[object]) bool
```

Please take a look at other parts of the source code and fix the Method Signature mismatch, if found more.

**Comment by hiddeco** [comment]
> It appears that `GenerationChangedPredicate` defines the Update method with a parameter named e, whereas `TypedPredicate[object]` expects an unnamed parameter. This results in an incompatibility when used in a generic context. 

This can not be true, and I suspect it is something an LLM told you. In Go (including generics), Interface satisfaction is based on method signatures (name, parameters, and return types) rather than parameter names.

I rather suspect this to be an IDE issue (assumingly, you make use of either GoLand or some other IntelliJ IDE), which appears to trip over the following code upstream: https://github.com/kubernetes-sigs/controller-runtime/blob/9d8d219840a43b60b1c70e59811bf54283ae9fe9/pkg/predicate/predicate.go#L32-L48

Including their very own: https://github.com/kubernetes-sigs/controller-runtime/blob/9d8d219840a43b60b1c70e59811bf54283ae9fe9/pkg/predicate/predicate.go#L187

See also:

![image](https://github.com/user-attachments/assets/29ec3335-34f3-40c8-9fb6-65c00836c8a3)

**Comment by hiddeco** [comment]
I also can not reproduce this after updating IntelliJ IDEA Ultimate from 2024.2.4 to 2024.3.3.
